---
extends:
  - stylelint-config-standard
plugins:
  - stylelint-csstree-validator
  - stylelint-declaration-block-no-ignored-properties
  - stylelint-high-performance-animation
  - stylelint-no-unsupported-browser-features
  - stylelint-order
  - stylelint-selector-tag-no-without-class
rules:
  # Based on:
  # https://github.com/hudochenkov/stylelint-config-hudochenkov/blob/master/index.js
  # https://github.com/keithamus/stylelint-config-strict/blob/master/index.js
  # https://github.com/twbs/stylelint-config-twbs-bootstrap/blob/main/css/index.js
  alpha-value-notation: number
  at-rule-empty-line-before:
    - always
    - except:
        - blockless-after-same-name-blockless
        - first-nested
      ignore:
        - after-comment
      ignoreAtRules:
        - else
  at-rule-name-space-after: always
  at-rule-no-vendor-prefix: true
  at-rule-semicolon-space-before: never
  block-closing-brace-newline-before: always
  block-closing-brace-space-after: always-single-line
  block-opening-brace-newline-after: always-multi-line
  color-named: never
  declaration-block-no-redundant-longhand-properties: true
  declaration-block-semicolon-newline-after: always
  declaration-block-semicolon-newline-before: never-multi-line
  declaration-empty-line-before:
    - always
    - except:
        - after-comment
        - after-declaration
        - first-nested
  declaration-no-important: true
  font-family-name-quotes: always-unless-keyword
  font-weight-notation: numeric
  function-comma-newline-before: never-multi-line
  # I prefer scheme relative URLs for better development without using SSL
  function-url-no-scheme-relative: null
  function-url-quotes: never
  indentation: 4
  max-line-length: 140
  max-nesting-depth: 5
  media-feature-name-no-unknown: true
  media-feature-name-no-vendor-prefix: null
  media-query-list-comma-newline-before: never-multi-line
  no-descending-specificity:
    - true
    - ignore: "selectors-within-list"
  no-unknown-animations: true
  number-leading-zero: never
  property-no-vendor-prefix: true
  selector-attribute-quotes: always
  selector-list-comma-newline-before: never-multi-line
  selector-list-comma-space-after: always-single-line
  selector-max-attribute: 1
  selector-max-class: 5
  selector-max-combinators: 5
  selector-max-compound-selectors: 5
  selector-max-empty-lines:
    - 0
    - severity: warning
  selector-max-id: 1
  selector-max-type: 2
  selector-max-universal: 0
  selector-no-qualifying-type:
    - true
    - ignore:
        - attribute
  selector-no-vendor-prefix: null
  shorthand-property-no-redundant-values: true
  string-quotes: single
  time-min-milliseconds:
    - 100
    - severity: warning
  unicode-bom: never
  unit-disallowed-list:
    - ch
    - cm
    - ex
    - in
    - mm
    - pc
    - pt
  value-keyword-case: lower
  value-list-comma-newline-after: always-multi-line
  value-list-comma-newline-before: never-multi-line
  value-list-comma-space-after: always-single-line
  value-list-comma-space-before: never
  value-no-vendor-prefix: true

  csstree/validator: true

  plugin/declaration-block-no-ignored-properties: true

  plugin/no-unsupported-browser-features:
    - true
    - severity: warning

  plugin/no-low-performance-animation-properties: true
  plugin/selector-tag-no-without-class:
    - div
    - span

  order/order:
    - custom-properties
    - dollar-variables
    - at-variables
    - at-rules
    - declarations
    - rules

  order/properties-alphabetical-order: true
