---
customHeaders:
  - pattern: '**'
    headers:
      - key: 'Cache-Control'
        value: 'Cache-Control: public, max-age=31536000, immutable'
      - key: 'Content-Security-Policy'
        value: >
          default-src 'none';
          font-src https://fonts.gstatic.com;
          img-src 'self';
          manifest-src 'self';
          script-src 'self' https://code.jquery.com/jquery-3.7.1.slim.min.js;
          style-src 'self' https://fonts.googleapis.com/
      - key: 'Referrer-Policy'
        value: 'same-origin'
      - key: 'Strict-Transport-Security'
        value: 'max-age=63072000; includeSubDomains; preload'
      - key: 'X-Content-Type-Options'
        value: 'nosniff'
      - key: 'X-Frame-Options'
        value: 'DENY'
      - key: 'X-XSS-Protection'
        value: '1; mode=block'
  - pattern: '**/*(*.html)'
    headers:
      - key: 'Cache-Control'
        value: 'Cache-Control: public, max-age=2592000, stale-while-revalidate=86400'
