---
customHeaders:
  - pattern: "**"
    headers:
      - key: "Cache-Control"
        value: "public, max-age=31536000"
      - key: "Content-Security-Policy"
        value: |
          base-uri 'self';
          connect-src 'self';
          default-src 'none';
          font-src 'self';
          form-action 'self';
          frame-ancestors 'none';
          img-src 'self';
          manifest-src 'self';
          script-src 'self' ${script_sri};
          style-src 'self' ${style_sri};
          worker-src 'self';
      - key: Cross-Origin-Opener-Policy
        value: same-origin
      # Not using this header until it supports deny-all
      # https://github.com/w3c/webappsec-permissions-policy/issues/189#issuecomment-2420730558
      # https://github.com/w3c/webappsec-permissions-policy/blob/main/permissions-policy-explainer.md
      # Generator: https://www.permissionspolicy.com/
      # - key: 'Permissions-Policy'
      #   value: deny-all
      - key: "Referrer-Policy"
        value: "same-origin"
        # https://brntn.me/blog/website-best-practices/#hsts-headers-must-be-returned
      - key: "Strict-Transport-Security"
        value: "max-age=63072000; includeSubDomains; preload"
      - key: "X-Content-Type-Options"
        value: "nosniff"
      - key: "X-Frame-Options"
        value: "DENY"
      - key: "X-XSS-Protection"
        value: "1; mode=block"
  - pattern: "/_astro/**"
    headers:
      - key: "Cache-Control"
        value: "public, max-age=31536000, immutable"
  - pattern: "**/*(*.html)"
    headers:
      - key: "Cache-Control"
        value: "public, max-age=2592000, stale-while-revalidate=86400"
