---
customHeaders:
  - pattern: '**'
    headers:
      - key: 'Cache-Control'
        value: 'Cache-Control: public, max-age=31536000'
      - key: 'Content-Security-Policy'
        value: >
          default-src 'none';
          connect-src 'self';
          font-src 'self';
          img-src 'self';
          manifest-src 'self';
          script-src 'self' ${script_sri};
          style-src 'self' ${style_sri};
          worker-src 'self';
      - key: 'Referrer-Policy'
        value: 'same-origin'
      - key: 'Strict-Transport-Security'
        value: 'max-age=63072000; includeSubDomains; preload'
      - key: 'X-Content-Type-Options'
        value: 'nosniff'
      - key: 'X-Frame-Options'
        value: 'DENY'
      - key: 'X-XSS-Protection'
        value: '1; mode=block'
  - pattern: '/_astro/**'
    headers:
      - key: 'Cache-Control'
        value: 'Cache-Control: public, max-age=31536000, immutable'
  - pattern: '**/*(*.html)'
    headers:
      - key: 'Cache-Control'
        value: 'Cache-Control: public, max-age=2592000, stale-while-revalidate=86400'
